#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: ${ssh_user}
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ${ssh_user_public_key}
write_files:
- content: |
    ${indent(4, netplan_yaml)}
  path: /etc/cloud/cloud.cfg.d/04_net.cfg
  permissions: '0755'
runcmd:
  - sleep 5
  - reboot
